apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-app
  namespace: prod
  labels: 
    app: reverse-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-app
  template:
    metadata:
      labels:
        app: reverse-app
    spec:
      containers:
      - name: reverse-app
        image: reverse-app
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-app-nextjs
  namespace: prod
spec:
  selector:
    app: reverse-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
